FROM mcr.microsoft.com/devcontainers/javascript-node:20

# Install additional tools if needed
# RUN apt-get update && apt-get install -y --no-install-recommends <packages>

# Set a default working directory
WORKDIR /workspace
